# Site settings
course_name: Deep Generative Models
course_description: "Explore the principles and techniques behind Deep Generative Models, including VAEs, GANs, and autoregressive models, to create and understand complex data distributions. This course combines theoretical foundations with practical applications to equip students with the skills to build and deploy generative models in various domains."
course_semester: "Fall 2024"

baseurl: "/dgm-penn" # the subpath of your site, e.g. /blog/
url: "https://kaleab-k.github.io/" # the base hostname & protocol for your site

schoolname: "University of Pennsylvania"
schoolurl: "https://www.upenn.edu/"
twitter_username: penn 

address: |
    University of Pennsylvania
    Philadelphia, PA 19104 
    United States

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
